# One entry per module video. access: 'all' | 'page:<id>' (global page, same rule as the sidebar) | 'tab:<id>' (outlet sheet)
T = lambda tab: {'page': 'salon', 'tab': tab}
G = lambda page: {'page': page}
GRP = {'basic': ('Getting started', 'शुरुआत'), 'global': ('Global pages', 'ग्लोबल पेज'), 'front': ('Front desk', 'फ्रंट डेस्क'),
       'pay': ('Payroll & HR', 'पेरोल और HR'), 'money': ('Money', 'पैसा और हिसाब'), 'rep': ('Reports & compliance', 'रिपोर्ट्स और कंप्लायंस')}
def M(id, icon, en, hi, grp, nav, access, who, topics, intro):
    return dict(id=id, icon=icon, title=(en, hi), group=GRP[grp], nav=nav, access=access, who=who, topics=topics, intro=intro)
MODULES = [
 M('basics', '🚀', 'Getting started', 'शुरुआत कैसे करें', 'basic', G('dashboard'), 'all',
   ('For everyone', 'सभी के लिए'),
   (['Sign in', 'Sidebar & outlets', 'Period', 'Sheet tabs', 'Search (Ctrl+F)', 'Save, alerts & help'],
    ['Sign in', 'Sidebar और outlets', 'Period', 'Sheet tabs', 'Search (Ctrl+F)', 'Save, alerts और help']),
   ("Getting started with SalonOS — signing in, moving around, and the buttons you will use on every screen.",
    "SalonOS की शुरुआत — sign in करना, software में घूमना, और वो buttons जो हर screen पर काम आते हैं।")),
 M('review', '✅', 'Review Centre', 'Review Centre', 'global', G('collaboration'), 'page:collaboration',
   ('Super Admin · Reviewer · staff who submit', 'Super Admin · Reviewer · submit करने वाला staff'),
   (['Submissions', 'Status filters', 'Approve or return', 'My Submissions'], ['Submissions', 'Status filters', 'Approve या return', 'My Submissions']),
   ("The Review Centre — where sheets sent for approval are checked, approved or returned.",
    "Review Centre — जहाँ approval के लिए भेजी गई sheets check, approve या वापस की जाती हैं।")),
 M('dashboard', '📊', 'Master Dashboard', 'Master Dashboard', 'global', G('dashboard'), 'page:dashboard',
   ('Owners · Super Admin · Managers', 'मालिक · Super Admin · Managers'),
   (['Outlet comparison', 'KPI cards', 'Revenue trend', 'Outlet & year filters'], ['Outlet comparison', 'KPI cards', 'Revenue trend', 'Outlet और year filter']),
   ("The Master Dashboard — all your outlets compared on one screen.", "Master Dashboard — आपके सभी outlets एक ही screen पर compare।")),
 M('insights', '💡', 'Owner Insights', 'Owner Insights', 'global', G('insights'), 'page:insights',
   ('Owners · Super Admin', 'मालिक · Super Admin'),
   (['Today at a glance', 'Month heading', 'Bills due', 'Team'], ['आज का हाल', 'महीने का अनुमान', 'Bills due', 'Team']),
   ("Owner Insights — today's position of every outlet at a glance.", "Owner Insights — हर outlet की आज की स्थिति एक नज़र में।")),
 M('master-sheet', '🏪', 'Master Sheet — outlets', 'Master Sheet — outlets', 'global', G('master-sheet'), 'page:master-sheet',
   ('Super Admin', 'Super Admin'),
   (['Outlet list', 'Add / edit outlet', 'Outlet settings', 'Bulk import', 'Month locks'], ['Outlet list', 'Outlet add / edit', 'Outlet settings', 'Bulk import', 'Month locks']),
   ("The Master Sheet — creating outlets and setting how each outlet works.", "Master Sheet — outlets बनाना और हर outlet की settings तय करना।")),
 M('reports-hub', '📋', 'Reports Hub', 'Reports Hub', 'global', G('reports'), 'page:reports',
   ('Owners · Super Admin · Accounts', 'मालिक · Super Admin · Accounts'),
   (['All-outlet reports', 'Month & outlet filters', 'Trend chart', 'Export'], ['सभी outlets की reports', 'Month और outlet filter', 'Trend chart', 'Export']),
   ("The Reports Hub — reports that combine all your outlets.", "Reports Hub — सभी outlets को जोड़ने वाली reports।")),
 M('pnl-statement', '📈', 'P&L Statement (all months)', 'P&L Statement (सभी महीने)', 'global', G('pnl'), 'page:pnl',
   ('Super Admin · Reviewer · Owner', 'Super Admin · Reviewer · Owner'),
   (['Year view', 'Month columns', 'Outlet filter', 'Share'], ['साल का view', 'महीनों के columns', 'Outlet filter', 'Share']),
   ("The P&L Statement — the whole financial year, month by month.", "P&L Statement — पूरा financial year, महीने-दर-महीने।")),
 M('users', '👥', 'User Management', 'User Management', 'global', G('users'), 'page:users',
   ('Super Admin', 'Super Admin'),
   (['Add user', 'Roles', 'Outlet access', 'Sheet access', 'Deactivate'], ['User जोड़ें', 'Roles', 'Outlet access', 'Sheet access', 'Deactivate']),
   ("User Management — creating logins and deciding exactly what each person can see and change.",
    "User Management — logins बनाना और तय करना कि कौन क्या देख और बदल सकता है।")),
 M('settings', '⚙', 'Master Settings', 'Master Settings', 'global', G('settings'), 'page:settings',
   ('Super Admin', 'Super Admin'),
   (['Backup & restore', 'Storage', 'Statutory (PF, ESIC, PT)', 'Salary configuration'], ['Backup और restore', 'Storage', 'Statutory (PF, ESIC, PT)', 'Salary configuration']),
   ("Master Settings — backup, statutory rules and company-wide salary settings.", "Master Settings — backup, statutory नियम और पूरी company की salary settings।")),
 M('outlet-dashboard', '📊', 'Outlet Dashboard', 'Outlet Dashboard', 'rep', T('outlet-dashboard'), 'tab:outlet-dashboard',
   ('Owners · Managers', 'मालिक · Managers'),
   (['Monthly overview', 'Month-on-month', 'P&L view', 'Period reports', 'Expenses summary'], ['Monthly overview', 'Month-on-month', 'P&L view', 'Period reports', 'Expenses summary']),
   ("The Outlet Dashboard — one outlet's month in numbers and charts.", "Outlet Dashboard — एक outlet का महीना, numbers और charts में।")),
 M('appointments', '📅', 'Appointments', 'Appointments', 'front', T('appointments'), 'tab:appointments',
   ('Front desk · Managers', 'Front desk · Managers'),
   (['Day book', 'New booking', 'Check-in & status', 'Staff filter', 'WhatsApp reminders'], ['Day book', 'नई booking', 'Check-in और status', 'Staff filter', 'WhatsApp reminders']),
   ("The Appointment Book — booking clients and running the day.", "Appointment Book — clients की booking और दिन को चलाना।")),
 M('billing', '🧾', 'Billing', 'Billing', 'front', T('billing'), 'tab:billing',
   ('Front desk · Managers', 'Front desk · Managers'),
   (['New bill', 'GST', 'Payment modes', 'Print / edit', 'Filters & export'], ['नया bill', 'GST', 'Payment modes', 'Print / edit', 'Filters और export']),
   ("Billing — the point of sale for services and products.", "Billing — services और products का point of sale।")),
 M('clients', '👥', 'Clients (CRM)', 'Clients (CRM)', 'front', T('clients'), 'tab:clients',
   ('Front desk · Managers', 'Front desk · Managers'),
   (['Client list', 'Segments', 'Client profile', 'WhatsApp offers'], ['Client list', 'Segments', 'Client profile', 'WhatsApp offers']),
   ("Clients — your client book, visits, spend and offers.", "Clients — आपकी client book, visits, खर्च और offers।")),
 M('inventory', '📦', 'Inventory', 'Inventory', 'front', T('inventory'), 'tab:inventory',
   ('Managers · Store', 'Managers · Store'),
   (['Stock value', 'Reorder alerts', 'Receive & issue', 'Purchase order'], ['Stock value', 'Reorder alerts', 'Receive और issue', 'Purchase order']),
   ("Inventory — backbar and retail stock, and what to reorder.", "Inventory — backbar और retail stock, और क्या मँगवाना है।")),
 M('master-salary', '💰', 'Master Salary (staff master)', 'Master Salary (staff master)', 'pay', T('master-salary'), 'tab:master-salary',
   ('HR · Accounts · Super Admin', 'HR · Accounts · Super Admin'),
   (['Employee list', 'Add / edit employee', 'Salary structure', 'Statutory flags', 'Import & export', 'Inactive employees'],
    ['Employee list', 'Employee add / edit', 'Salary structure', 'Statutory flags', 'Import और export', 'Inactive employees']),
   ("Master Salary — the staff master behind attendance, salary and incentives.", "Master Salary — staff master, जिस पर attendance, salary और incentive चलते हैं।")),
 M('daily-sales', '💵', 'Daily Sales & Expenses', 'Daily Sales & Expenses', 'money', T('daily-sales'), 'tab:daily-sales',
   ('Salon Manager · Data entry', 'Salon Manager · Data entry'),
   (['Expense rows', 'Employee & invoice rows', 'Sales & collection', 'Cash balance', 'Cash register check', 'Month final'],
    ['Expense rows', 'Employee और invoice rows', 'Sales और collection', 'Cash balance', 'Cash register check', 'Month final']),
   ("Daily Sales and Expenses — the most important daily entry in SalonOS.", "Daily Sales & Expenses — SalonOS की सबसे ज़रूरी रोज़ की entry।")),
 M('attendance', '✅', 'Attendance', 'Attendance', 'pay', T('attendance'), 'tab:attendance',
   ('Salon Manager', 'Salon Manager'),
   (['Mark a day', 'Statuses', 'Summary', 'Full register', 'Bulk upload', 'Month final'], ['दिन mark करें', 'Statuses', 'Summary', 'Full register', 'Bulk upload', 'Month final']),
   ("Attendance — marking every employee's day, which drives salary.", "Attendance — हर employee का दिन mark करना, जिससे salary बनती है।")),
 M('salary-working', '📋', 'Salary Working', 'Salary Working', 'pay', T('salary-working'), 'tab:salary-working',
   ('Accounts · Super Admin · Managers (approval)', 'Accounts · Super Admin · Managers (approval)'),
   (['Generate salary', 'Columns', 'Deductions', 'Payslips & challans', 'Lock & approve', 'Salary payment'],
    ['Salary generate', 'Columns', 'Deductions', 'Payslips और challans', 'Lock और approve', 'Salary payment']),
   ("Salary Working — calculating, checking and finalising the month's salary.", "Salary Working — महीने की salary calculate, check और final करना।")),
 M('incentive-working', '🏆', 'Incentive Working', 'Incentive Working', 'pay', T('incentive-working'), 'tab:incentive-working',
   ('Accounts · Super Admin · Managers (approval)', 'Accounts · Super Admin · Managers (approval)'),
   (['Targets & achieved', 'Rules & settings', 'Overtime (OT)', 'Share workings', 'Lock & approve', 'Staff work report'],
    ['Targets और achieved', 'Rules और settings', 'Overtime (OT)', 'Share workings', 'Lock और approve', 'Staff work report']),
   ("Incentive Working — monthly incentives from targets, sales and overtime.", "Incentive Working — targets, sales और overtime से monthly incentive।")),
 M('daily-incentive', '🎯', 'Daily Incentive', 'Daily Incentive', 'pay', T('daily-incentive'), 'tab:daily-incentive',
   ('Salon Manager · Accounts', 'Salon Manager · Accounts'),
   (['Entries', 'Sync from attendance', 'Tips', 'Staff overtime'], ['Entries', 'Attendance से sync', 'Tips', 'Staff overtime']),
   ("Daily Incentive — commissions, tips and overtime paid day by day.", "Daily Incentive — रोज़ दिए गए commission, tips और overtime।")),
 M('advance', '💳', 'Advances', 'Advances', 'pay', T('advance'), 'tab:advance',
   ('Salon Manager · ASM · Accounts', 'Salon Manager · ASM · Accounts'),
   (['Request advance', 'Approval', 'Deduction schedule', 'Register & report'], ['Advance request', 'Approval', 'Deduction schedule', 'Register और report']),
   ("Advances — money given to staff and how it is recovered from salary.", "Advances — staff को दिया पैसा और salary से उसकी वसूली।")),
 M('penalty', '⚠️', 'Penalties', 'Penalties', 'pay', T('penalty'), 'tab:penalty',
   ('Salon Manager · Accounts', 'Salon Manager · Accounts'),
   (['Add penalty', 'Types', 'Recovery', 'Export'], ['Penalty जोड़ें', 'Types', 'Recovery', 'Export']),
   ("Penalties — recording fines and recovering them from salary.", "Penalties — fines दर्ज करना और salary से वसूलना।")),
 M('vendors', '🏭', 'Vendors & bills', 'Vendors और bills', 'money', T('vendors'), 'tab:vendors',
   ('Accounts · Salon Manager', 'Accounts · Salon Manager'),
   (['Vendor master', 'Add invoice', 'Payments', 'Outstanding', 'Proforma invoices', 'Bulk import'],
    ['Vendor master', 'Invoice जोड़ें', 'Payments', 'Outstanding', 'Proforma invoices', 'Bulk import']),
   ("The Vendor Sheet — every vendor, every bill and every payment.", "Vendor Sheet — हर vendor, हर bill और हर payment।")),
 M('due-dates', '📌', 'Due Dates', 'Due Dates', 'money', T('due-dates'), 'tab:due-dates',
   ('Accounts · Super Admin', 'Accounts · Super Admin'),
   (['Auto items', 'Filters', 'Mark paid', 'Add your own'], ['Auto items', 'Filters', 'Mark paid', 'अपनी due date जोड़ें']),
   ("Due Dates — everything that has to be paid, and when.", "Due Dates — जो कुछ pay करना है, और कब।")),
 M('bank-statement', '🏦', 'Bank Statement', 'Bank Statement', 'money', T('bank-statement'), 'tab:bank-statement',
   ('Accounts · Super Admin', 'Accounts · Super Admin'),
   (['Download from bank', 'Import', 'Nature & mapping', 'Link payments', 'Export'], ['Bank से download', 'Import', 'Nature और mapping', 'Payments link', 'Export']),
   ("The Bank Statement — importing your bank statement and classifying every line.", "Bank Statement — bank statement import करना और हर line classify करना।")),
 M('bank-payment', '🏧', 'Bank Payment', 'Bank Payment', 'money', T('bank-payment'), 'tab:bank-payment',
   ('Accounts · Super Admin', 'Accounts · Super Admin'),
   (['Bank format', 'NEFT / RTGS', 'Salary', 'Incentive', 'Vendor payments'], ['Bank format', 'NEFT / RTGS', 'Salary', 'Incentive', 'Vendor payments']),
   ("Bank Payment — making bulk payment files for your bank.", "Bank Payment — bank के लिए bulk payment file बनाना।")),
 M('recurring-expenses', '🔁', 'Recurring Expenses', 'Recurring Expenses', 'money', T('recurring-expenses'), 'tab:recurring-expenses',
   ('Accounts · Super Admin', 'Accounts · Super Admin'),
   (['Fixed & variable', 'Frequency & billing', 'Enter bill', 'Estimates & adjustments', 'Register', 'Pay online'],
    ['Fixed और variable', 'Frequency और billing', 'Bill दर्ज करें', 'Estimate और adjustment', 'Register', 'Online pay']),
   ("Recurring Expenses — rent, electricity and every bill that repeats.", "Recurring Expenses — rent, बिजली और हर दोहराने वाला bill।")),
 M('fixed-assets', '🏢', 'Fixed Assets', 'Fixed Assets', 'money', T('fixed-assets'), 'tab:fixed-assets',
   ('Accounts · Super Admin', 'Accounts · Super Admin'),
   (['Assets register', 'Book an asset', 'Depreciation', 'Blocks & rates'], ['Assets register', 'Asset book करें', 'Depreciation', 'Blocks और rates']),
   ("Fixed Assets — equipment and furniture, and their depreciation.", "Fixed Assets — equipment और furniture, और उनका depreciation।")),
 M('collection', '📥', 'Collection Summary (import)', 'Collection Summary (import)', 'money', T('collection'), 'tab:collection',
   ('Accounts · Salon Manager', 'Accounts · Salon Manager'),
   (['Get the report', 'Import', 'Auto-import folder', 'Preview & export'], ['Report लाना', 'Import', 'Auto-import folder', 'Preview और export']),
   ("Collection Summary — importing day-wise collection from your billing software.", "Collection Summary — billing software से day-wise collection import करना।")),
 M('collection-sheet', '📊', 'Collection Reco', 'Collection Reco', 'money', T('collection-sheet'), 'tab:collection-sheet',
   ('Accounts · Super Admin', 'Accounts · Super Admin'),
   (['Three-way match', 'Differences', 'Reasons', 'Bank charges', 'Filters & share'], ['तीन-तरफ़ा मिलान', 'Differences', 'Reasons', 'Bank charges', 'Filters और share']),
   ("Collection Reco — matching billing, counter and bank, every day.", "Collection Reco — billing, counter और bank का रोज़ मिलान।")),
 M('outlet-pnl', '📈', 'P&L (Monthly)', 'P&L (Monthly)', 'rep', T('outlet-pnl'), 'tab:outlet-pnl',
   ('Owners · Accounts · Super Admin', 'मालिक · Accounts · Super Admin'),
   (['Statement', 'Drill-down', 'Overrides', 'Variance & cash flow', 'Mark as Final', 'Export'],
    ['Statement', 'Drill-down', 'Overrides', 'Variance और cash flow', 'Mark as Final', 'Export']),
   ("P&L Monthly — the outlet's profit and loss for one month.", "P&L Monthly — एक महीने का outlet का profit और loss।")),
 M('previous-pnl', '🗂️', 'Previous Months P&L', 'Previous Months P&L', 'rep', T('previous-pnl'), 'tab:previous-pnl',
   ('Accounts · Super Admin', 'Accounts · Super Admin'),
   (['Add a month', 'Template', 'Bulk import'], ['Month जोड़ें', 'Template', 'Bulk import']),
   ("Previous Months P&L — history from before you started SalonOS.", "Previous Months P&L — SalonOS शुरू होने से पहले का history।")),
 M('tally-export', '🔄', 'Tally Export', 'Tally Export', 'rep', T('tally-export'), 'tab:tally-export',
   ('Accounts · Super Admin', 'Accounts · Super Admin'),
   (['Connector', 'Overview', 'Vouchers & preview', 'Ledger mapping', 'History', 'Settings'],
    ['Connector', 'Overview', 'Vouchers और preview', 'Ledger mapping', 'History', 'Settings']),
   ("Tally Export — moving SalonOS entries into Tally, safely and with a preview.", "Tally Export — SalonOS की entries को सुरक्षित तरीके से, preview के साथ Tally में भेजना।")),
 M('reports', '📇', 'Reports', 'Reports', 'rep', T('reports'), 'tab:reports',
   ('Accounts · Owners', 'Accounts · मालिक'),
   (['Cash register', 'Expense register', 'Expenses summary', 'TDS, PF, ESIC, PT', 'Fund position'], ['Cash register', 'Expense register', 'Expenses summary', 'TDS, PF, ESIC, PT', 'Fund position']),
   ("Reports — the ready registers and statutory summaries of one outlet.", "Reports — एक outlet के तैयार registers और statutory summaries।")),
 M('audit-log', '🕵', 'Audit Log', 'Audit Log', 'rep', T('audit-log'), 'tab:audit-log',
   ('Super Admin · Owners', 'Super Admin · मालिक'),
   (['Who changed what', 'Filters', 'Search'], ['किसने क्या बदला', 'Filters', 'Search']),
   ("The Audit Log — who changed what, and when.", "Audit Log — किसने, क्या और कब बदला।")),
 M('import-center', '📥', 'Import Center', 'Import Center', 'rep', T('import-center'), 'tab:import-center',
   ('Accounts · Super Admin', 'Accounts · Super Admin'),
   (['Templates', 'Staff import', 'Vendor import', 'Incentive import', 'Other imports'], ['Templates', 'Staff import', 'Vendor import', 'Incentive import', 'बाकी imports']),
   ("The Import Center — every Excel template and bulk upload in one place.", "Import Center — हर Excel template और bulk upload एक जगह।")),
]
